# Generated by Django 6.0.2 on 2026-03-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FarmManager", "0008_add_cluster_number_to_farm"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="farm",
            options={"ordering": ["farm_id"]},
        ),
        migrations.AlterModelOptions(
            name="reproduction",
            options={
                "ordering": [
                    models.OrderBy(
                        models.F("heat_sign_recorded_at"),
                        descending=True,
                        nulls_last=True,
                    )
                ]
            },
        ),
        migrations.AddField(
            model_name="inseminationrecord",
            name="date_of_insemination",
            field=models.DateField(
                blank=True, help_text="Date when insemination was performed", null=True
            ),
        ),
    ]
